# kubectl create secret generic google-key --from-file=key.json=gcp-credential.json
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autocomplete
  labels:
    app: autocomplete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocomplete
  template:
    metadata:
      labels:
        app: autocomplete
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-key
      - name: web-certs
        secret:
          secretName: tls-cert-key
      containers:
      - name: autocomplete
        image: gcr.io/typeahead-183622/github-rickcrawford-gcp-autocomplete.es:29533c5567c0ba2888b6e963d3986dc0817e807e
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
        - name: web-certs
          mountPath: /var/secrets/certs
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: HTTP_PORT
          value: "80"
        - name: HTTPS_PORT
          value: "443"
        - name: ELASTIC_URL
          value: http://elasticsearch:9200
        - name: REDIS_URL
          value: redis://redis:6379
        - name: TLS_CERTIFICATE
          value: /var/secrets/certs/tls.crt
        - name: TLS_PRIVATE_KEY
          value: /var/secrets/certs/tls.key
        ports:
        - containerPort: 80
        - containerPort: 443