apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: autocomplete
spec:
  tls:
  - hosts:
    - service.typeahead.com
    secretName: tls-cert-key
  rules:
  - host: service.typeahead.com
    http:
      paths:
      - backend:
          serviceName: autocomplete
          servicePort: 80